name: Pull Request CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v23
      - uses: DeterminateSystems/magic-nix-cache-action@v15
      - uses: DeterminateSystems/flake-checker-action@v14
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
      - name: Run `nix build`
        run: nix build
        timeout-minutes: 20
      - name: Run `nix flake check`
        run: nix flake check --option max-jobs 1
        timeout-minutes: 20
